name: products
server:
  port: 10000
zipkin:
  enable: true	
  server: http://localhost:9411   
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ofbiz?statementInterceptors=org.efbiz.brave.MySQLStatementInterceptor&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    connectionTestQuery: SELECT 1
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 5
    minimumIdle: 1
  cloud:
    config:
      label: master
      profile: dev     
endpoints:
 shutdown:
  enabled: true 