name: products
server:
  port: 10000
spring:
  application:
    name: products
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ofbiz?statementInterceptors=com.github.kristofa.brave.mysql.MySQLStatementInterceptor&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
    connectionTestQuery: SELECT 1
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 5
    minimumIdle: 1
mybatis:
    mapperLocations: classpath:mybatis/*/*/*.xml
    typeAliasesPackage: org.efbiz.product
    configLocation: classpath:configuration.xml